### ISSUE TITLE
Not receiving msgs after a while

### ISSUE THREAD

**Issue by adizag** [inUtil-info/node-red-contrib-whin#6]
@lu4t 
1st - tnx for great plugin!!!

Installed it today, tested it and everything worked perfectly.
When I wanted to show off it to my wife after about 2 hours, suddenly the "whin-receive" node was not showing any output both in my phone and my wife's.
Node-red container restart didn't work.
modified-nodes deployment didn't work.
Only after full deployment, it gotbback to work.

Any Idea?

**Comment by alsak0de** [comment]
Not really. If you restarted the container, I suppose that would restart all flows just like a full deployment so I don't see how that didn't work and the deployment did.

**Comment by lu4t** [comment]
> @lu4t 1st - tnx for great plugin!!!
> 
> Installed it today, tested it and everything worked perfectly. When I wanted to show off it to my wife after about 2 hours, suddenly the "whin-receive" node was not showing any output both in my phone and my wife's. Node-red container restart didn't work. modified-nodes deployment didn't work. Only after full deployment, it gotbback to work.
> 
> Any Idea?

hi @adizag, it's great that you find whin useful... 
there's not a enough info to debug what might have happened on you environment, next time please grab some logs and post it so that we can have a look.
We already had users who were trying to create flows talking to different whatsapp numbers (tipically all the family members and stuff like that).... in this case, bear in mind that each node (receiver and sender) is a point-to-point link between whin and a given whatsapp user. This means that you want to have a config for you, and a config (different) for your wife (each config has different token/number pair).
If you follow this principle, you should not have a problem sending /receiving a whatsapp from your wife's phone on your node-red instance.
Keep using whin and have fun!!

**Comment by adizag** [comment]
Ok! I found the problem... 
very strange - I'm using WhatsApp web on my PC.
from WhatsApp web - the receiving node is getting the message, but from the phone directly it is not!

made sure - sent "signup" from both, I get the same token of course.
Strange!

**Comment by lu4t** [comment]
Great! Good that you solved the issue 😀

**Comment by adizag** [comment]
@lu4t  unfortunately it is not solved... just found the root cause.
Any idea how to solve it?

**Comment by lu4t** [comment]
> @lu4t unfortunately it is not solved... just found the root cause. Any idea how to solve it?

This is not something we can debug properly with the info you provide.  
FYI: The receiver node is just listener, it will grab any message you write to whin, and whin will forward it (encrypted) to your node-red environment.  There's no difference on which whatsapp client you're using, the receive node does not interact with whatsapp at all, so sending from whatsapp web or mobile app doesn't make any difference...

One important thing you need to consider: if node-red editor is not open, you won't see the message on the debug node... so it might be the receiver is getting the messages sent from the phone, but you're not able to see them flowing (unless you have a logger that saves all the messages).
